variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test

image: python:3

before_script:
  -  pip install -r requirements.txt

python_black_test:
  stage: test
  script:
    - python -m black .

unittest:
  stage: test
  script:
    - python -m pytest